image: $CI_IMAGE

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

flake8:
    script:
        - flake8 .
    allow_failure: false

test:
    before_script:
        - apt-get update && apt-get install -y fonts-lato
        - pip3 install .[bokeh,matplotlib]
    script:
        - ./run_tests.sh
    artifacts:
        paths:
            - example_plots/
    allow_failure: false
